name: CI

on:
  push:
    branches:
      - 'main'
      - '*.*'
      - '!*backport*'
      - '*'
    tags:
      - 'v*'
      - '!*dev*'
      - '!*pre*'
      - '!*post*'
  pull_request:

  # Allow manual runs through the web UI
  #workflow_dispatch:

jobs:
  core:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      posargs: -n auto
      envs: |
        - linux: codestyle
        - linux: py311
      coverage: 'codecov'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test:
    needs: [core]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      submodules: false
      coverage: codecov
      posargs: -n auto
      envs: |
        - macos: py311-test
        - windows: py311-test
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  doc:
    needs: [test]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      default_python: '3.11'
      submodules: false
      pytest: false
      libraries: |
        apt:
          - libopenjp2-7
          - graphviz
      envs: |
        - linux: build_docs
